[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/contracts/src/v0.8/automation/=lib/chainlink-brownie-contracts/contracts/src/v0.8/automation/",
    "@chainlink/contracts/src/v0.8/interfaces/=lib/chainlink-brownie-contracts/contracts/src/v0.8/shared/interfaces/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@pythnetwork/=lib/pyth-sdk-solidity/",
    "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[rpc_endpoints]
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
bsc_mainnet = "https://bsc-dataseed.binance.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
